#include<stdio.h>
#include<conio.h>
void main()
{
int side1,side2,side3;
clrscr();
printf("input the sides of triangle:");
scanf("%d %d %d",&side1, &side2, &side3);
if(side1==side2 &&side2==side3)
{
printf("this is an equilateral triangle\n");
}
else if(side1==side2||side1==side3||side2==side3)
{
printf("this is an isosceles triangle\n");
}
else
{
printf("this is a scalene triangle\n");
}
getch();
}
